version: '3'
services:
    influxdb:
        image: influxdb:latest
        volumes:
            - influxdb-storage:/var/lib/influxdb2:rw
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=inverter
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_USERNAME}
    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
    influxdb-storage:
    grafana-storage:
