name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./bt
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install libdbus-1-dev
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --all --release
    - name: Run tests
      run: cargo test --verbose
